api_key: "" # 请替换为有效的 DeepSeek API Key
ai_name: "dwgx"
available_models:
  - deepseek-chat
  - deepseek-reasoner
  - deepseek-coder
  - deepseek-pro
ai_whitelist: []
player_message_limits: {}

ai_public_prompt: |
  你是一个Minecraft 1.21.4服务器AI助手，名字叫“{ai_name}”。根据玩家输入，提供自然友好的文本回复，不生成命令（以/开头）。若无法理解，回复“{ai_name}不太明白，能再解释一下吗？”。可以根据玩家状态和历史对话自由发挥，提供建议或创意。
  玩家状态: {player_context}
  历史摘要: {history}
  当前输入: {message}

ai_admin_prompt: |
  你是一个Minecraft 1.21.4服务器的高级AI助手，名字叫“{ai_name}”。任务：根据管理员输入，生成直接可执行的Minecraft命令（每行以 / 开头，多行用 \n 分隔，仅输出命令，不附加任何说明或纯文本）。支持高级操作，如复杂建筑生成、批量物品分发、动态效果应用等。确保命令符合Minecraft语法，避免生成无效或危险命令（如/stop、/reload、/op）。若无法理解，返回 '/say {ai_name} 无法理解，请明确需求'。
  玩家状态: {player_context}
  历史摘要: {history}
  背包: {inventory}
  效果: {effects}
  世界资源: {world_resources}
  当前输入: {message}

ai_welcome_enabled: true
ai_welcome_interval: 3600000
message_reset_interval: 72000
chat_history_max_size: 10

blocking:
  enabled: true
  damage-reduce-percentage: 50
  reduce-only-entity-damage: true
  enable-vanilla-blocking: true

npc_enabled: true
npc_locations:
  - world,188.500000,125.000000,30.500000,179.999634,11.250050,auto_107

dashboard_enabled: true
dashboard_chat_limit: 5

freeze:
  enabled: true
  persist_across_relog: false

sitting:
  enabled: true
  allowSittingOnBlocks: true
  allowSittingOnPlayers: true
  blocked-worlds: []
  valid-blocks:
    - stair
    - slab
    - step